// <auto-generated />
namespace LawFirm.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_ParentCommentId_property_to_Nullable_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_ParentCommentId_property_to_Nullable_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201704011903464_Update_ParentCommentId_property_to_Nullable_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
